FROM docker.io/dunglas/frankenphp:latest AS builder

ARG USER=docker

ENV SERVER_ROOT=/app
ENV SERVER_NAME=:8080

WORKDIR /app

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends git zip unzip

RUN mv "${PHP_INI_DIR}/php.ini-production" "${PHP_INI_DIR}/php.ini" && \
    install-php-extensions \
    pdo_mysql \
    gettext \
    gd \
    intl \
    zip \
    opcache

RUN useradd --system --no-create-home --shell /sbin/nologin ${USER}
RUN chown -R ${USER}:${USER} /config /data

RUN apt-get autoremove -y && apt-get clean -y && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

FROM builder as stage

WORKDIR /app

RUN rm -rf /app/* && \
    git clone --depth 1 -b develop https://github.com/spotweb/spotweb.git /app

FROM builder as production

WORKDIR /app

COPY --chown=docker:docker --from=stage /app /app
COPY --chown=docker:docker containers/runtimes/dbsettings.inc.php /app/dbsettings.inc.php

USER docker
