#!/bin/sh

# Build images

podman build \
    -t spotweb-nginx \
    --file=build/nginx/Dockerfile \
    --env=../../.env \
    --no-cache

podman build \
    -t spotweb-app \
    --file=build/app/Dockerfile \
    --env=../../.env \
    --no-cache
